import turtle
t=turtle.Turtle()
t.turtlesize(2.5,2.5,2.5)
turtle.Screen().setup(1300,700)
t.shape('turtle')
t.penup()
i=0
for i in range(0,7):
    t.forward(75)
    if i == 0:
        t.color('red')
        t.speed(5)
        t.penup()
        t.goto(-620,-20)
        t.pendown()
        t.right(105)
        t.circle(405,-150)
        t.penup()
    elif i ==1:
        t.color('orange')
        t.speed(5)
        t.penup()
        t.goto(-619.7,-20)
        t.left(146)
        t.pendown()
        t.circle(404.8,-142)
        t.penup()
    elif i ==2:
        t.color('yellow')
        t.speed(5)
        t.penup()
        t.goto(-619.5,-20)
        t.pendown()
        t.left(138)
        t.circle(404.6,-135)
        t.penup()
    elif i ==3:
        t.color('green')
        t.speed(5)
        t.penup()
        t.goto(-619.3,-20)
        t.pendown()
        t.left(132)
        t.circle(404.4,-129)
        t.penup()
    elif i ==4:
        t.color('blue')
        t.speed(5)
        t.penup()
        t.goto(-619.1,-20)
        t.pendown()
        t.left(125)
        t.circle(404.2,-122)
        t.penup()
    elif i ==5:
        t.color('indigo')
        t.speed(5)
        t.penup()
        t.goto(-618.9,-20)
        t.pendown()
        t.left(120)
        t.circle(404,-118.2)
        t.penup()
    elif i ==6:
        t.color('violet')
        t.speed(5)
        t.penup()
        t.goto(-618.7,-20)
        t.pendown()
        t.left(114)
        t.circle(403.8,-112)
        t.penup()
    t.stamp()
